---
- name: Create telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    backup: true

- name: Start and Enable Telegraf
  service:
    name: telegraf
    state: started
    enabled: true