---
- name: Create telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    backup: true
  notify:
    - Restart telegraf

- name: Start and Enable telegraf
  service:
    name: telegraf
    state: started
    enabled: true