---
- name: Telegraf | Create telegraf.conf
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    backup: true
    owner: telegraf
    group: telegraf
  notify:
    - Restart telegraf

- name: Get services facts
  service_facts:

- include: configure-docker.yml
  when: "'docker.service' in services"

- name: Telegraf | Add custom config to telegraf.d
  copy:
    src: "{{ item }}"
    dest: /etc/telegraf/telegraf.d/
    owner: telegraf
    group: telegraf
  with_fileglob: "{{ telegraf_custom_config_files }}"
  notify:
    - Restart telegraf

- name: Telegraf | Start and Enable telegraf
  service:
    name: telegraf
    state: started
    enabled: true