---
- name: Telegraf | Install telegraf from URL [Debian/Ubuntu]
  apt:
    deb: "{{ telegraf_mirror | default('https://dl.influxdata.com/telegraf/releases') }}/telegraf_{{ telegraf_version }}_{{ telegraf_arch }}.deb"
    state: present