---
- name: Telegraf | Install telegraf from URL [RHEL/CentOS]
  yum:
    name: "{{ telegraf_mirror | default('https://dl.influxdata.com/telegraf/releases') }}/telegraf-{{telegraf_version}}.{{telegraf_arch}}.rpm"
    state: present